import dayjs from "dayjs";

export interface TripDetail {
  tripId: string;
  vehicleNo: string;
  driverName: string;
  driverPhone: string;
  transporter: string;
  lrNo: string;
  dispatchDate: string;
  deliveryDate?: string;
  status: "Delivered" | "In Transit" | "Unloaded" | "Dispatched" | "Pending";
  destinationGodown: string;
  loadingPoint: string;
}

export type DeliveryStatus =
  | "Arrived Today"
  | "Arrived Earlier"
  | "Not Delivered"
  | "In Transit"
  | "Pending Delivery";

export type PaymentStatus = "Paid" | "Partial" | "Unpaid";

export interface OrderItemDetail {
  id: string;
  itemNo: number;
  itemName: string;
  qty: string;
  tonnage: number;
  rate: number;
  itemValue: number;
  arrivalDate: string;
  status: DeliveryStatus;
  tripDetail?: TripDetail;
}

export interface WholeOrderDetails {
  orderId: string;
  orderDate: string;
  retailerName: string;
  city: string;
  state: string;
  totalOrderTonnage: number;
  totalOrderValue: number;
  paymentStatus: PaymentStatus;
  paidAmount: number;
  balanceAmount: number;
  items: OrderItemDetail[];
}

export type PurchaseReportFilterType =
  | "today_arrival"
  | "pending_orders"
  | "pending_payments"
  | "completed";

export interface TodayArrivalItem {
  id: string;
  sNo: number;
  date: string;
  orderId: string;
  itemName: string;
  retailerName: string;
  city: string;
  state: string;
  qty?: string;
  tonnage: number;
  itemValue: number;
  statusTag?: string;
  order: WholeOrderDetails;
}

// Backward compatibility alias
export type PurchasePartySummary = TodayArrivalItem;
export type PurchaseReportItem = TodayArrivalItem;

export const DUMMY_PURCHASE_DATA: TodayArrivalItem[] = [
  {
    id: "arr-1",
    sNo: 1,
    date: "15/09/2026",
    orderId: "ORD-2026-0841",
    itemName: "ROYAL-GOLD WHITEGRAM-AA 30KG",
    retailerName: "RAVI INDUSTRIES",
    city: "INDORE",
    state: "MADHYA PRADESH",
    qty: "400 Bags",
    tonnage: 12.0,
    itemValue: 1260000,
    order: {
      orderId: "ORD-2026-0841",
      orderDate: "28/08/2026",
      retailerName: "RAVI INDUSTRIES",
      city: "INDORE",
      state: "MADHYA PRADESH",
      totalOrderTonnage: 44.0,
      totalOrderValue: 4580000,
      paymentStatus: "Partial",
      paidAmount: 3000000,
      balanceAmount: 1580000,
      items: [
        {
          id: "item-1-1",
          itemNo: 1,
          itemName: "ROYAL-GOLD WHITEGRAM-AA 30KG",
          qty: "400 Bags",
          tonnage: 12.0,
          rate: 105000,
          itemValue: 1260000,
          arrivalDate: "15/09/2026",
          status: "Arrived Today",
          tripDetail: {
            tripId: "TRIP-8801",
            vehicleNo: "MP 09 GH 4521",
            driverName: "Ramesh Sharma",
            driverPhone: "+91 98260 12345",
            transporter: "Swastik Roadlines",
            lrNo: "SW-89211",
            dispatchDate: "09/09/2026",
            deliveryDate: "15/09/2026",
            status: "Delivered",
            destinationGodown: "Central Godown - Unit 1",
            loadingPoint: "Indore Mandi",
          },
        },
        {
          id: "item-1-2",
          itemNo: 2,
          itemName: "PREMIUM URAD DHALL 30KG",
          qty: "350 Bags",
          tonnage: 10.5,
          rate: 110000,
          itemValue: 1155000,
          arrivalDate: "03/09/2026",
          status: "Arrived Earlier",
          tripDetail: {
            tripId: "TRIP-8760",
            vehicleNo: "MP 09 BC 8890",
            driverName: "Dinesh Verma",
            driverPhone: "+91 98260 54321",
            transporter: "Swastik Roadlines",
            lrNo: "SW-88910",
            dispatchDate: "01/09/2026",
            deliveryDate: "03/09/2026",
            status: "Delivered",
            destinationGodown: "Central Godown - Unit 1",
            loadingPoint: "Indore Mandi",
          },
        },
        {
          id: "item-1-3",
          itemNo: 3,
          itemName: "YELLOW TOOR WHOLE 50KG",
          qty: "300 Bags",
          tonnage: 15.0,
          rate: 85000,
          itemValue: 1275000,
          arrivalDate: "06/09/2026",
          status: "Arrived Earlier",
          tripDetail: {
            tripId: "TRIP-8785",
            vehicleNo: "MP 09 CD 7741",
            driverName: "Mukesh Yadav",
            driverPhone: "+91 98260 67890",
            transporter: "Express Cargo Lines",
            lrNo: "EC-90112",
            dispatchDate: "04/09/2026",
            deliveryDate: "06/09/2026",
            status: "Delivered",
            destinationGodown: "South Godown Hub",
            loadingPoint: "Indore Mandi",
          },
        },
        {
          id: "item-1-4",
          itemNo: 4,
          itemName: "CHANA SPECIAL DESI 30KG",
          qty: "216 Bags",
          tonnage: 6.5,
          rate: 137000,
          itemValue: 890000,
          arrivalDate: "-",
          status: "Pending Delivery",
          tripDetail: undefined,
        },
      ],
    },
  },
  {
    id: "arr-2",
    sNo: 2,
    date: "15/09/2026",
    orderId: "ORD-2026-0842",
    itemName: "1000 WHITEGRAM-AA 30KG",
    retailerName: "TAMILNADU TRADERS",
    city: "VIRUDHUNAGAR",
    state: "TAMIL NADU",
    qty: "500 Bags",
    tonnage: 15.0,
    itemValue: 1290000,
    order: {
      orderId: "ORD-2026-0842",
      orderDate: "29/08/2026",
      retailerName: "TAMILNADU TRADERS",
      city: "VIRUDHUNAGAR",
      state: "TAMIL NADU",
      totalOrderTonnage: 47.0,
      totalOrderValue: 4235000,
      paymentStatus: "Paid",
      paidAmount: 4235000,
      balanceAmount: 0,
      items: [
        {
          id: "item-2-1",
          itemNo: 1,
          itemName: "1000 WHITEGRAM-AA 30KG",
          qty: "500 Bags",
          tonnage: 15.0,
          rate: 86000,
          itemValue: 1290000,
          arrivalDate: "15/09/2026",
          status: "Arrived Today",
          tripDetail: {
            tripId: "TRIP-8803",
            vehicleNo: "TN 67 AB 1234",
            driverName: "K. Murugan",
            driverPhone: "+91 94431 11223",
            transporter: "Southern Logistics",
            lrNo: "SL-44102",
            dispatchDate: "08/09/2026",
            deliveryDate: "15/09/2026",
            status: "Delivered",
            destinationGodown: "Madurai Terminal",
            loadingPoint: "Virudhunagar Yard",
          },
        },
        {
          id: "item-2-2",
          itemNo: 2,
          itemName: "MOONG WHOLE SPECIAL 50KG",
          qty: "300 Bags",
          tonnage: 15.0,
          rate: 86000,
          itemValue: 1290000,
          arrivalDate: "04/09/2026",
          status: "Arrived Earlier",
          tripDetail: {
            tripId: "TRIP-8772",
            vehicleNo: "TN 67 CD 5678",
            driverName: "S. Selvam",
            driverPhone: "+91 94431 44556",
            transporter: "Southern Logistics",
            lrNo: "SL-44018",
            dispatchDate: "02/09/2026",
            deliveryDate: "04/09/2026",
            status: "Delivered",
            destinationGodown: "Madurai Terminal",
            loadingPoint: "Virudhunagar Yard",
          },
        },
        {
          id: "item-2-3",
          itemNo: 3,
          itemName: "GREEN MOONG DHALL 30KG",
          qty: "300 Bags",
          tonnage: 9.0,
          rate: 95000,
          itemValue: 855000,
          arrivalDate: "07/09/2026",
          status: "Arrived Earlier",
          tripDetail: {
            tripId: "TRIP-8790",
            vehicleNo: "TN 67 EF 9012",
            driverName: "M. Pandi",
            driverPhone: "+91 94431 77889",
            transporter: "Royal Roadways",
            lrNo: "RR-10294",
            dispatchDate: "05/09/2026",
            deliveryDate: "07/09/2026",
            status: "Delivered",
            destinationGodown: "Madurai Terminal",
            loadingPoint: "Virudhunagar Yard",
          },
        },
        {
          id: "item-2-4",
          itemNo: 4,
          itemName: "FRIED GRAM (POTTUKADALAI) 25KG",
          qty: "320 Bags",
          tonnage: 8.0,
          rate: 100000,
          itemValue: 800000,
          arrivalDate: "-",
          status: "Pending Delivery",
          tripDetail: undefined,
        },
      ],
    },
  },
  {
    id: "arr-3",
    sNo: 3,
    date: "15/09/2026",
    orderId: "ORD-2026-0843",
    itemName: "RAM TOOR-DHALL 30KG",
    retailerName: "SHREE RAM TRADERS",
    city: "GONDAL",
    state: "GUJARAT",
    qty: "200 Bags",
    tonnage: 6.0,
    itemValue: 792000,
    order: {
      orderId: "ORD-2026-0843",
      orderDate: "30/08/2026",
      retailerName: "SHREE RAM TRADERS",
      city: "GONDAL",
      state: "GUJARAT",
      totalOrderTonnage: 36.0,
      totalOrderValue: 4712000,
      paymentStatus: "Partial",
      paidAmount: 2500000,
      balanceAmount: 2212000,
      items: [
        {
          id: "item-3-1",
          itemNo: 1,
          itemName: "RAM TOOR-DHALL 30KG",
          qty: "200 Bags",
          tonnage: 6.0,
          rate: 132000,
          itemValue: 792000,
          arrivalDate: "15/09/2026",
          status: "Arrived Today",
          tripDetail: {
            tripId: "TRIP-8805",
            vehicleNo: "GJ 03 AX 9911",
            driverName: "Hitesh Patel",
            driverPhone: "+91 98240 11223",
            transporter: "Gujarat Saurashtra Freight",
            lrNo: "GS-77210",
            dispatchDate: "08/09/2026",
            deliveryDate: "15/09/2026",
            status: "Delivered",
            destinationGodown: "Western Regional Godown",
            loadingPoint: "Gondal Market Yard",
          },
        },
        {
          id: "item-3-2",
          itemNo: 2,
          itemName: "CHANA DHALL SUPER 30KG",
          qty: "400 Bags",
          tonnage: 12.0,
          rate: 132000,
          itemValue: 1584000,
          arrivalDate: "05/09/2026",
          status: "Arrived Earlier",
          tripDetail: {
            tripId: "TRIP-8780",
            vehicleNo: "GJ 03 BY 4455",
            driverName: "Bhavesh Makwana",
            driverPhone: "+91 98240 44556",
            transporter: "Gujarat Saurashtra Freight",
            lrNo: "GS-77119",
            dispatchDate: "02/09/2026",
            deliveryDate: "05/09/2026",
            status: "Delivered",
            destinationGodown: "Western Regional Godown",
            loadingPoint: "Gondal Market Yard",
          },
        },
        {
          id: "item-3-3",
          itemNo: 3,
          itemName: "KABULI CHANA MEDIUM 50KG",
          qty: "200 Bags",
          tonnage: 10.0,
          rate: 145000,
          itemValue: 1450000,
          arrivalDate: "08/09/2026",
          status: "Arrived Earlier",
          tripDetail: {
            tripId: "TRIP-8798",
            vehicleNo: "GJ 03 CZ 1122",
            driverName: "Jayesh Solanki",
            driverPhone: "+91 98240 77889",
            transporter: "Speedex Logistics",
            lrNo: "SX-66512",
            dispatchDate: "06/09/2026",
            deliveryDate: "08/09/2026",
            status: "Delivered",
            destinationGodown: "Western Regional Godown",
            loadingPoint: "Gondal Market Yard",
          },
        },
        {
          id: "item-3-4",
          itemNo: 4,
          itemName: "MOONG WHOLE ORGANIC 30KG",
          qty: "266 Bags",
          tonnage: 8.0,
          rate: 110750,
          itemValue: 886000,
          arrivalDate: "-",
          status: "Pending Delivery",
          tripDetail: undefined,
        },
      ],
    },
  },
  {
    id: "arr-4",
    sNo: 4,
    date: "15/09/2026",
    orderId: "ORD-2026-0844",
    itemName: "URAD GOTA SPECIAL 30KG",
    retailerName: "MANN ENTERPRISES",
    city: "JAORA",
    state: "MADHYA PRADESH",
    qty: "200 Bags",
    tonnage: 6.0,
    itemValue: 558000,
    order: {
      orderId: "ORD-2026-0844",
      orderDate: "01/09/2026",
      retailerName: "MANN ENTERPRISES",
      city: "JAORA",
      state: "MADHYA PRADESH",
      totalOrderTonnage: 32.0,
      totalOrderValue: 3108000,
      paymentStatus: "Unpaid",
      paidAmount: 0,
      balanceAmount: 3108000,
      items: [
        {
          id: "item-4-1",
          itemNo: 1,
          itemName: "URAD GOTA SPECIAL 30KG",
          qty: "200 Bags",
          tonnage: 6.0,
          rate: 93000,
          itemValue: 558000,
          arrivalDate: "15/09/2026",
          status: "Arrived Today",
          tripDetail: {
            tripId: "TRIP-8807",
            vehicleNo: "MP 43 CA 6677",
            driverName: "Sunil Rathore",
            driverPhone: "+91 99810 11223",
            transporter: "Malwa Express",
            lrNo: "ME-22104",
            dispatchDate: "09/09/2026",
            deliveryDate: "15/09/2026",
            status: "Delivered",
            destinationGodown: "Ratlam Depot",
            loadingPoint: "Jaora Mandi",
          },
        },
        {
          id: "item-4-2",
          itemNo: 2,
          itemName: "MASOOR DHALL FOOTBALL 30KG",
          qty: "200 Bags",
          tonnage: 6.0,
          rate: 93000,
          itemValue: 558000,
          arrivalDate: "04/09/2026",
          status: "Arrived Earlier",
          tripDetail: {
            tripId: "TRIP-8775",
            vehicleNo: "MP 43 DB 8899",
            driverName: "Kailash Mali",
            driverPhone: "+91 99810 44556",
            transporter: "Malwa Express",
            lrNo: "ME-22015",
            dispatchDate: "02/09/2026",
            deliveryDate: "04/09/2026",
            status: "Delivered",
            destinationGodown: "Ratlam Depot",
            loadingPoint: "Jaora Mandi",
          },
        },
        {
          id: "item-4-3",
          itemNo: 3,
          itemName: "CHANA WHOLE BOLD 50KG",
          qty: "200 Bags",
          tonnage: 10.0,
          rate: 102000,
          itemValue: 1020000,
          arrivalDate: "07/09/2026",
          status: "Arrived Earlier",
          tripDetail: {
            tripId: "TRIP-8792",
            vehicleNo: "MP 43 EA 1123",
            driverName: "Devendra Jat",
            driverPhone: "+91 99810 77889",
            transporter: "Central Transport Hub",
            lrNo: "CT-90812",
            dispatchDate: "05/09/2026",
            deliveryDate: "07/09/2026",
            status: "Delivered",
            destinationGodown: "Ratlam Depot",
            loadingPoint: "Jaora Mandi",
          },
        },
        {
          id: "item-4-4",
          itemNo: 4,
          itemName: "GREEN PEAS DRIED 50KG",
          qty: "200 Bags",
          tonnage: 10.0,
          rate: 97200,
          itemValue: 972000,
          arrivalDate: "-",
          status: "Pending Delivery",
          tripDetail: undefined,
        },
      ],
    },
  },
  {
    id: "arr-5",
    sNo: 5,
    date: "15/09/2026",
    orderId: "ORD-2026-0845",
    itemName: "CHANA DHALL REGULAR 30KG",
    retailerName: "SAMRAT INDUSTRIES",
    city: "RAJKOT",
    state: "GUJARAT",
    qty: "266 Bags",
    tonnage: 8.0,
    itemValue: 1096000,
    order: {
      orderId: "ORD-2026-0845",
      orderDate: "02/09/2026",
      retailerName: "SAMRAT INDUSTRIES",
      city: "RAJKOT",
      state: "GUJARAT",
      totalOrderTonnage: 38.0,
      totalOrderValue: 5122000,
      paymentStatus: "Paid",
      paidAmount: 5122000,
      balanceAmount: 0,
      items: [
        {
          id: "item-5-1",
          itemNo: 1,
          itemName: "CHANA DHALL REGULAR 30KG",
          qty: "266 Bags",
          tonnage: 8.0,
          rate: 137000,
          itemValue: 1096000,
          arrivalDate: "15/09/2026",
          status: "Arrived Today",
          tripDetail: {
            tripId: "TRIP-8809",
            vehicleNo: "GJ 04 AA 1188",
            driverName: "Pravin Bhai",
            driverPhone: "+91 98250 11223",
            transporter: "Saurashtra Transporters",
            lrNo: "ST-88901",
            dispatchDate: "09/09/2026",
            deliveryDate: "15/09/2026",
            status: "Delivered",
            destinationGodown: "North-West Yard",
            loadingPoint: "Rajkot Industrial Area",
          },
        },
        {
          id: "item-5-2",
          itemNo: 2,
          itemName: "WHITE PEAS (VATANA) 50KG",
          qty: "160 Bags",
          tonnage: 8.0,
          rate: 137000,
          itemValue: 1096000,
          arrivalDate: "05/09/2026",
          status: "Arrived Earlier",
          tripDetail: {
            tripId: "TRIP-8782",
            vehicleNo: "GJ 04 BB 3344",
            driverName: "Kishore Parmar",
            driverPhone: "+91 98250 44556",
            transporter: "Saurashtra Transporters",
            lrNo: "ST-88812",
            dispatchDate: "03/09/2026",
            deliveryDate: "05/09/2026",
            status: "Delivered",
            destinationGodown: "North-West Yard",
            loadingPoint: "Rajkot Industrial Area",
          },
        },
        {
          id: "item-5-3",
          itemNo: 3,
          itemName: "TOOR DHALL PHATKA 30KG",
          qty: "400 Bags",
          tonnage: 12.0,
          rate: 140000,
          itemValue: 1680000,
          arrivalDate: "08/09/2026",
          status: "Arrived Earlier",
          tripDetail: {
            tripId: "TRIP-8795",
            vehicleNo: "GJ 04 CC 7788",
            driverName: "Mansukh Chavda",
            driverPhone: "+91 98250 77889",
            transporter: "Rajkot Speed Lines",
            lrNo: "RSL-33412",
            dispatchDate: "06/09/2026",
            deliveryDate: "08/09/2026",
            status: "Delivered",
            destinationGodown: "North-West Yard",
            loadingPoint: "Rajkot Industrial Area",
          },
        },
        {
          id: "item-5-4",
          itemNo: 4,
          itemName: "SOYA BEAN SEED 50KG",
          qty: "200 Bags",
          tonnage: 10.0,
          rate: 125000,
          itemValue: 1250000,
          arrivalDate: "-",
          status: "Pending Delivery",
          tripDetail: undefined,
        },
      ],
    },
  },
  {
    id: "arr-6",
    sNo: 6,
    date: "15/09/2026",
    orderId: "ORD-2026-0846",
    itemName: "MASOOR WHOLE PREMIUM 50KG",
    retailerName: "M.S.TRADERS",
    city: "MADURAI",
    state: "TAMIL NADU",
    qty: "180 Bags",
    tonnage: 9.0,
    itemValue: 657000,
    order: {
      orderId: "ORD-2026-0846",
      orderDate: "03/09/2026",
      retailerName: "M.S.TRADERS",
      city: "MADURAI",
      state: "TAMIL NADU",
      totalOrderTonnage: 36.0,
      totalOrderValue: 2628000,
      paymentStatus: "Partial",
      paidAmount: 1800000,
      balanceAmount: 828000,
      items: [
        {
          id: "item-6-1",
          itemNo: 1,
          itemName: "MASOOR WHOLE PREMIUM 50KG",
          qty: "180 Bags",
          tonnage: 9.0,
          rate: 73000,
          itemValue: 657000,
          arrivalDate: "15/09/2026",
          status: "Arrived Today",
          tripDetail: {
            tripId: "TRIP-8811",
            vehicleNo: "TN 59 AB 9988",
            driverName: "S. Karuppasamy",
            driverPhone: "+91 94420 11223",
            transporter: "Madurai Cargo Lines",
            lrNo: "MC-44120",
            dispatchDate: "09/09/2026",
            deliveryDate: "15/09/2026",
            status: "Delivered",
            destinationGodown: "South Zone Main Godown",
            loadingPoint: "Madurai Anuppanadi Yard",
          },
        },
        {
          id: "item-6-2",
          itemNo: 2,
          itemName: "URAD DHALL SPLIT 30KG",
          qty: "300 Bags",
          tonnage: 9.0,
          rate: 73000,
          itemValue: 657000,
          arrivalDate: "06/09/2026",
          status: "Arrived Earlier",
          tripDetail: {
            tripId: "TRIP-8788",
            vehicleNo: "TN 59 CD 1122",
            driverName: "V. Thangavel",
            driverPhone: "+91 94420 44556",
            transporter: "Madurai Cargo Lines",
            lrNo: "MC-44090",
            dispatchDate: "04/09/2026",
            deliveryDate: "06/09/2026",
            status: "Delivered",
            destinationGodown: "South Zone Main Godown",
            loadingPoint: "Madurai Anuppanadi Yard",
          },
        },
        {
          id: "item-6-3",
          itemNo: 3,
          itemName: "CHANA BROWN GRADE-A 50KG",
          qty: "180 Bags",
          tonnage: 9.0,
          rate: 75000,
          itemValue: 675000,
          arrivalDate: "08/09/2026",
          status: "Arrived Earlier",
          tripDetail: {
            tripId: "TRIP-8800",
            vehicleNo: "TN 59 EF 3344",
            driverName: "K. Manikandan",
            driverPhone: "+91 94420 77889",
            transporter: "Sri Meenakshi Transports",
            lrNo: "SM-11290",
            dispatchDate: "06/09/2026",
            deliveryDate: "08/09/2026",
            status: "Delivered",
            destinationGodown: "South Zone Main Godown",
            loadingPoint: "Madurai Anuppanadi Yard",
          },
        },
        {
          id: "item-6-4",
          itemNo: 4,
          itemName: "CORIANDER WHOLE 25KG",
          qty: "360 Bags",
          tonnage: 9.0,
          rate: 71000,
          itemValue: 639000,
          arrivalDate: "-",
          status: "Pending Delivery",
          tripDetail: undefined,
        },
      ],
    },
  },
  {
    id: "arr-7",
    sNo: 7,
    date: "15/09/2026",
    orderId: "ORD-2026-0847",
    itemName: "TOOR DHALL PREMIUM 30KG",
    retailerName: "SRI MURUGAN AGRO",
    city: "THANJAVUR",
    state: "TAMIL NADU",
    qty: "333 Bags",
    tonnage: 10.0,
    itemValue: 980000,
    order: {
      orderId: "ORD-2026-0847",
      orderDate: "04/09/2026",
      retailerName: "SRI MURUGAN AGRO",
      city: "THANJAVUR",
      state: "TAMIL NADU",
      totalOrderTonnage: 37.0,
      totalOrderValue: 3626000,
      paymentStatus: "Paid",
      paidAmount: 3626000,
      balanceAmount: 0,
      items: [
        {
          id: "item-7-1",
          itemNo: 1,
          itemName: "TOOR DHALL PREMIUM 30KG",
          qty: "333 Bags",
          tonnage: 10.0,
          rate: 98000,
          itemValue: 980000,
          arrivalDate: "15/09/2026",
          status: "Arrived Today",
          tripDetail: {
            tripId: "TRIP-8813",
            vehicleNo: "TN 49 AZ 1212",
            driverName: "A. Rajendran",
            driverPhone: "+91 98424 11223",
            transporter: "Cauvery Roadways",
            lrNo: "CR-90801",
            dispatchDate: "09/09/2026",
            deliveryDate: "15/09/2026",
            status: "Delivered",
            destinationGodown: "Delta Agro Godown",
            loadingPoint: "Thanjavur Old Bus Stand Yard",
          },
        },
        {
          id: "item-7-2",
          itemNo: 2,
          itemName: "MOONG DHALL YELLOW 30KG",
          qty: "333 Bags",
          tonnage: 10.0,
          rate: 98000,
          itemValue: 980000,
          arrivalDate: "07/09/2026",
          status: "Arrived Earlier",
          tripDetail: {
            tripId: "TRIP-8794",
            vehicleNo: "TN 49 BY 3434",
            driverName: "S. Balan",
            driverPhone: "+91 98424 44556",
            transporter: "Cauvery Roadways",
            lrNo: "CR-90715",
            dispatchDate: "05/09/2026",
            deliveryDate: "07/09/2026",
            status: "Delivered",
            destinationGodown: "Delta Agro Godown",
            loadingPoint: "Thanjavur Old Bus Stand Yard",
          },
        },
        {
          id: "item-7-3",
          itemNo: 3,
          itemName: "BLACK GRAM WHOLE 50KG",
          qty: "180 Bags",
          tonnage: 9.0,
          rate: 96000,
          itemValue: 864000,
          arrivalDate: "09/09/2026",
          status: "Arrived Earlier",
          tripDetail: {
            tripId: "TRIP-8802",
            vehicleNo: "TN 49 CX 5656",
            driverName: "K. Natarajan",
            driverPhone: "+91 98424 77889",
            transporter: "Trichy Logistics Hub",
            lrNo: "TL-55120",
            dispatchDate: "07/09/2026",
            deliveryDate: "09/09/2026",
            status: "Delivered",
            destinationGodown: "Delta Agro Godown",
            loadingPoint: "Thanjavur Old Bus Stand Yard",
          },
        },
        {
          id: "item-7-4",
          itemNo: 4,
          itemName: "WHITE GRAM BOLD 30KG",
          qty: "266 Bags",
          tonnage: 8.0,
          rate: 100250,
          itemValue: 802000,
          arrivalDate: "-",
          status: "Pending Delivery",
          tripDetail: undefined,
        },
      ],
    },
  },
  {
    id: "arr-8",
    sNo: 8,
    date: "15/09/2026",
    orderId: "ORD-2026-0848",
    itemName: "CHANA DAL SUPER FINE 30KG",
    retailerName: "GLOBAL COMMODITIES",
    city: "AHMEDABAD",
    state: "GUJARAT",
    qty: "500 Bags",
    tonnage: 15.0,
    itemValue: 1725000,
    order: {
      orderId: "ORD-2026-0848",
      orderDate: "05/09/2026",
      retailerName: "GLOBAL COMMODITIES",
      city: "AHMEDABAD",
      state: "GUJARAT",
      totalOrderTonnage: 48.0,
      totalOrderValue: 5520000,
      paymentStatus: "Partial",
      paidAmount: 3500000,
      balanceAmount: 2020000,
      items: [
        {
          id: "item-8-1",
          itemNo: 1,
          itemName: "CHANA DAL SUPER FINE 30KG",
          qty: "500 Bags",
          tonnage: 15.0,
          rate: 115000,
          itemValue: 1725000,
          arrivalDate: "15/09/2026",
          status: "Arrived Today",
          tripDetail: {
            tripId: "TRIP-8815",
            vehicleNo: "GJ 01 WW 5544",
            driverName: "Bipin Patel",
            driverPhone: "+91 98250 11445",
            transporter: "National Speed Cargo",
            lrNo: "NSC-8005",
            dispatchDate: "09/09/2026",
            deliveryDate: "15/09/2026",
            status: "Delivered",
            destinationGodown: "Ahmedabad Mega Terminal",
            loadingPoint: "Sanand Agro Hub",
          },
        },
        {
          id: "item-8-2",
          itemNo: 2,
          itemName: "KABULI CHANA BOLD 50KG",
          qty: "200 Bags",
          tonnage: 10.0,
          rate: 115000,
          itemValue: 1150000,
          arrivalDate: "08/09/2026",
          status: "Arrived Earlier",
          tripDetail: {
            tripId: "TRIP-8799",
            vehicleNo: "GJ 01 XX 7712",
            driverName: "Chetan Parmar",
            driverPhone: "+91 98250 99881",
            transporter: "National Speed Cargo",
            lrNo: "NSC-8012",
            dispatchDate: "06/09/2026",
            deliveryDate: "08/09/2026",
            status: "Delivered",
            destinationGodown: "Ahmedabad Mega Terminal",
            loadingPoint: "Sanand Agro Hub",
          },
        },
        {
          id: "item-8-3",
          itemNo: 3,
          itemName: "TURMERIC WHOLE SALEM 50KG",
          qty: "220 Bags",
          tonnage: 11.0,
          rate: 112000,
          itemValue: 1232000,
          arrivalDate: "09/09/2026",
          status: "Arrived Earlier",
          tripDetail: {
            tripId: "TRIP-8804",
            vehicleNo: "GJ 01 YY 9933",
            driverName: "Jignesh Joshi",
            driverPhone: "+91 98250 33445",
            transporter: "Apex Logistics",
            lrNo: "AL-77190",
            dispatchDate: "07/09/2026",
            deliveryDate: "09/09/2026",
            status: "Delivered",
            destinationGodown: "Ahmedabad Mega Terminal",
            loadingPoint: "Sanand Agro Hub",
          },
        },
        {
          id: "item-8-4",
          itemNo: 4,
          itemName: "JEERA WHOLE UNJHA 30KG",
          qty: "400 Bags",
          tonnage: 12.0,
          rate: 117750,
          itemValue: 1413000,
          arrivalDate: "-",
          status: "Pending Delivery",
          tripDetail: undefined,
        },
      ],
    },
  },
];

/* ================= PENDING ORDERS DATA ================= */
export const DUMMY_PENDING_ORDERS_DATA: TodayArrivalItem[] = [
  {
    id: "pend-1",
    sNo: 1,
    date: "15/09/2026",
    orderId: "ORD-2026-0841",
    itemName: "CHANA SPECIAL DESI 30KG",
    retailerName: "RAVI INDUSTRIES",
    city: "INDORE",
    state: "MADHYA PRADESH",
    qty: "216 Bags",
    tonnage: 6.5,
    itemValue: 890000,
    statusTag: "Pending Delivery",
    order: DUMMY_PURCHASE_DATA[0].order,
  },
  {
    id: "pend-2",
    sNo: 2,
    date: "15/09/2026",
    orderId: "ORD-2026-0842",
    itemName: "FRIED GRAM (POTTUKADALAI) 25KG",
    retailerName: "TAMILNADU TRADERS",
    city: "VIRUDHUNAGAR",
    state: "TAMIL NADU",
    qty: "320 Bags",
    tonnage: 8.0,
    itemValue: 800000,
    statusTag: "Pending Delivery",
    order: DUMMY_PURCHASE_DATA[1].order,
  },
  {
    id: "pend-3",
    sNo: 3,
    date: "15/09/2026",
    orderId: "ORD-2026-0843",
    itemName: "MOONG WHOLE ORGANIC 30KG",
    retailerName: "SHREE RAM TRADERS",
    city: "GONDAL",
    state: "GUJARAT",
    qty: "266 Bags",
    tonnage: 8.0,
    itemValue: 886000,
    statusTag: "Pending Delivery",
    order: DUMMY_PURCHASE_DATA[2].order,
  },
  {
    id: "pend-4",
    sNo: 4,
    date: "15/09/2026",
    orderId: "ORD-2026-0844",
    itemName: "GREEN PEAS DRIED 50KG",
    retailerName: "MANN ENTERPRISES",
    city: "JAORA",
    state: "MADHYA PRADESH",
    qty: "200 Bags",
    tonnage: 10.0,
    itemValue: 972000,
    statusTag: "Pending Delivery",
    order: DUMMY_PURCHASE_DATA[3].order,
  },
  {
    id: "pend-5",
    sNo: 5,
    date: "15/09/2026",
    orderId: "ORD-2026-0845",
    itemName: "SOYA BEAN SEED 50KG",
    retailerName: "SAMRAT INDUSTRIES",
    city: "RAJKOT",
    state: "GUJARAT",
    qty: "200 Bags",
    tonnage: 10.0,
    itemValue: 1250000,
    statusTag: "Pending Delivery",
    order: DUMMY_PURCHASE_DATA[4].order,
  },
  {
    id: "pend-6",
    sNo: 6,
    date: "15/09/2026",
    orderId: "ORD-2026-0846",
    itemName: "CORIANDER WHOLE 25KG",
    retailerName: "M.S.TRADERS",
    city: "MADURAI",
    state: "TAMIL NADU",
    qty: "360 Bags",
    tonnage: 9.0,
    itemValue: 639000,
    statusTag: "Pending Delivery",
    order: DUMMY_PURCHASE_DATA[5].order,
  },
  {
    id: "pend-7",
    sNo: 7,
    date: "15/09/2026",
    orderId: "ORD-2026-0847",
    itemName: "WHITE GRAM BOLD 30KG",
    retailerName: "SRI MURUGAN AGRO",
    city: "THANJAVUR",
    state: "TAMIL NADU",
    qty: "266 Bags",
    tonnage: 8.0,
    itemValue: 802000,
    statusTag: "Pending Delivery",
    order: DUMMY_PURCHASE_DATA[6].order,
  },
  {
    id: "pend-8",
    sNo: 8,
    date: "15/09/2026",
    orderId: "ORD-2026-0848",
    itemName: "JEERA WHOLE UNJHA 30KG",
    retailerName: "GLOBAL COMMODITIES",
    city: "AHMEDABAD",
    state: "GUJARAT",
    qty: "400 Bags",
    tonnage: 12.0,
    itemValue: 1413000,
    statusTag: "Pending Delivery",
    order: DUMMY_PURCHASE_DATA[7].order,
  },
];

/* ================= PENDING PAYMENTS DATA ================= */
export const DUMMY_PENDING_PAYMENTS_DATA: TodayArrivalItem[] = [
  {
    id: "pay-1",
    sNo: 1,
    date: "28/08/2026",
    orderId: "ORD-2026-0841",
    itemName: "ROYAL-GOLD WHITEGRAM-AA (4 Items Ordered)",
    retailerName: "RAVI INDUSTRIES",
    city: "INDORE",
    state: "MADHYA PRADESH",
    qty: "1,266 Bags",
    tonnage: 44.0,
    itemValue: 1580000,
    statusTag: "Partial Due",
    order: DUMMY_PURCHASE_DATA[0].order,
  },
  {
    id: "pay-2",
    sNo: 2,
    date: "30/08/2026",
    orderId: "ORD-2026-0843",
    itemName: "RAM TOOR-DHALL (4 Items Ordered)",
    retailerName: "SHREE RAM TRADERS",
    city: "GONDAL",
    state: "GUJARAT",
    qty: "1,066 Bags",
    tonnage: 36.0,
    itemValue: 2212000,
    statusTag: "Partial Due",
    order: DUMMY_PURCHASE_DATA[2].order,
  },
  {
    id: "pay-3",
    sNo: 3,
    date: "01/09/2026",
    orderId: "ORD-2026-0844",
    itemName: "URAD GOTA SPECIAL (4 Items Ordered)",
    retailerName: "MANN ENTERPRISES",
    city: "JAORA",
    state: "MADHYA PRADESH",
    qty: "866 Bags",
    tonnage: 32.0,
    itemValue: 3108000,
    statusTag: "Unpaid",
    order: DUMMY_PURCHASE_DATA[3].order,
  },
  {
    id: "pay-4",
    sNo: 4,
    date: "03/09/2026",
    orderId: "ORD-2026-0846",
    itemName: "MASOOR WHOLE PREMIUM (4 Items Ordered)",
    retailerName: "M.S.TRADERS",
    city: "MADURAI",
    state: "TAMIL NADU",
    qty: "1,060 Bags",
    tonnage: 36.0,
    itemValue: 828000,
    statusTag: "Partial Due",
    order: DUMMY_PURCHASE_DATA[5].order,
  },
  {
    id: "pay-5",
    sNo: 5,
    date: "05/09/2026",
    orderId: "ORD-2026-0848",
    itemName: "CHANA DAL SUPER FINE (4 Items Ordered)",
    retailerName: "GLOBAL COMMODITIES",
    city: "AHMEDABAD",
    state: "GUJARAT",
    qty: "1,400 Bags",
    tonnage: 48.0,
    itemValue: 2020000,
    statusTag: "Partial Due",
    order: DUMMY_PURCHASE_DATA[7].order,
  },
];

/* ================= COMPLETED ORDERS DATA ================= */
export const DUMMY_COMPLETED_DATA: TodayArrivalItem[] = [
  {
    id: "comp-1",
    sNo: 1,
    date: "25/08/2026",
    orderId: "ORD-2026-0831",
    itemName: "PREMIUM MOONG WHOLE 50KG",
    retailerName: "ROYAL AGRO TECH",
    city: "NAGPUR",
    state: "MAHARASHTRA",
    qty: "400 Bags",
    tonnage: 42.0,
    itemValue: 4450000,
    statusTag: "Delivered & Paid",
    order: {
      orderId: "ORD-2026-0831",
      orderDate: "15/08/2026",
      retailerName: "ROYAL AGRO TECH",
      city: "NAGPUR",
      state: "MAHARASHTRA",
      totalOrderTonnage: 42.0,
      totalOrderValue: 4450000,
      paymentStatus: "Paid",
      paidAmount: 4450000,
      balanceAmount: 0,
      items: [
        {
          id: "item-c1-1",
          itemNo: 1,
          itemName: "PREMIUM MOONG WHOLE 50KG",
          qty: "400 Bags",
          tonnage: 20.0,
          rate: 105000,
          itemValue: 2100000,
          arrivalDate: "20/08/2026",
          status: "Arrived Earlier",
          tripDetail: {
            tripId: "TRIP-8711",
            vehicleNo: "MH 31 AA 5544",
            driverName: "Dinesh Kadam",
            driverPhone: "+91 98230 44556",
            transporter: "Vidarbha Express",
            lrNo: "VE-11029",
            dispatchDate: "18/08/2026",
            deliveryDate: "20/08/2026",
            status: "Delivered",
            destinationGodown: "Central Godown - Unit 1",
            loadingPoint: "Nagpur Grain Mandi",
          },
        },
        {
          id: "item-c1-2",
          itemNo: 2,
          itemName: "TOOR DHALL PREMIUM 30KG",
          qty: "440 Bags",
          tonnage: 22.0,
          rate: 106818,
          itemValue: 2350000,
          arrivalDate: "25/08/2026",
          status: "Arrived Earlier",
          tripDetail: {
            tripId: "TRIP-8730",
            vehicleNo: "MH 31 BB 9988",
            driverName: "Vinod Raut",
            driverPhone: "+91 98230 99881",
            transporter: "Vidarbha Express",
            lrNo: "VE-11201",
            dispatchDate: "22/08/2026",
            deliveryDate: "25/08/2026",
            status: "Delivered",
            destinationGodown: "Central Godown - Unit 1",
            loadingPoint: "Nagpur Grain Mandi",
          },
        },
      ],
    },
  },
  {
    id: "comp-2",
    sNo: 2,
    date: "26/08/2026",
    orderId: "ORD-2026-0832",
    itemName: "CHANA BOLD GRADE-1 30KG",
    retailerName: "GUJARAT GRAIN TRADERS",
    city: "SURAT",
    state: "GUJARAT",
    qty: "500 Bags",
    tonnage: 38.5,
    itemValue: 3920000,
    statusTag: "Delivered & Paid",
    order: {
      orderId: "ORD-2026-0832",
      orderDate: "16/08/2026",
      retailerName: "GUJARAT GRAIN TRADERS",
      city: "SURAT",
      state: "GUJARAT",
      totalOrderTonnage: 38.5,
      totalOrderValue: 3920000,
      paymentStatus: "Paid",
      paidAmount: 3920000,
      balanceAmount: 0,
      items: [
        {
          id: "item-c2-1",
          itemNo: 1,
          itemName: "CHANA BOLD GRADE-1 30KG",
          qty: "500 Bags",
          tonnage: 20.0,
          rate: 102000,
          itemValue: 2040000,
          arrivalDate: "22/08/2026",
          status: "Arrived Earlier",
          tripDetail: {
            tripId: "TRIP-8722",
            vehicleNo: "GJ 05 YY 4433",
            driverName: "Ketan Desai",
            driverPhone: "+91 98251 11223",
            transporter: "Surat Express Cargo",
            lrNo: "SEC-9021",
            dispatchDate: "19/08/2026",
            deliveryDate: "22/08/2026",
            status: "Delivered",
            destinationGodown: "Western Regional Godown",
            loadingPoint: "Surat APMC",
          },
        },
        {
          id: "item-c2-2",
          itemNo: 2,
          itemName: "WHITE GRAM AA 30KG",
          qty: "370 Bags",
          tonnage: 18.5,
          rate: 101621,
          itemValue: 1880000,
          arrivalDate: "26/08/2026",
          status: "Arrived Earlier",
          tripDetail: {
            tripId: "TRIP-8735",
            vehicleNo: "GJ 05 ZZ 8877",
            driverName: "Haresh Vala",
            driverPhone: "+91 98251 55667",
            transporter: "Surat Express Cargo",
            lrNo: "SEC-9145",
            dispatchDate: "23/08/2026",
            deliveryDate: "26/08/2026",
            status: "Delivered",
            destinationGodown: "Western Regional Godown",
            loadingPoint: "Surat APMC",
          },
        },
      ],
    },
  },
  {
    id: "comp-3",
    sNo: 3,
    date: "27/08/2026",
    orderId: "ORD-2026-0833",
    itemName: "URAD DHALL PREMIUM 30KG",
    retailerName: "MADURAI PULSES CORP",
    city: "MADURAI",
    state: "TAMIL NADU",
    qty: "450 Bags",
    tonnage: 45.0,
    itemValue: 4860000,
    statusTag: "Delivered & Paid",
    order: {
      orderId: "ORD-2026-0833",
      orderDate: "18/08/2026",
      retailerName: "MADURAI PULSES CORP",
      city: "MADURAI",
      state: "TAMIL NADU",
      totalOrderTonnage: 45.0,
      totalOrderValue: 4860000,
      paymentStatus: "Paid",
      paidAmount: 4860000,
      balanceAmount: 0,
      items: [
        {
          id: "item-c3-1",
          itemNo: 1,
          itemName: "URAD DHALL PREMIUM 30KG",
          qty: "450 Bags",
          tonnage: 22.5,
          rate: 108000,
          itemValue: 2430000,
          arrivalDate: "24/08/2026",
          status: "Arrived Earlier",
          tripDetail: {
            tripId: "TRIP-8740",
            vehicleNo: "TN 58 BB 1122",
            driverName: "C. Alagarsamy",
            driverPhone: "+91 94432 11223",
            transporter: "Pandian Freight",
            lrNo: "PF-44210",
            dispatchDate: "21/08/2026",
            deliveryDate: "24/08/2026",
            status: "Delivered",
            destinationGodown: "South Zone Main Godown",
            loadingPoint: "Madurai Anuppanadi Yard",
          },
        },
        {
          id: "item-c3-2",
          itemNo: 2,
          itemName: "FRIED GRAM BULK 25KG",
          qty: "450 Bags",
          tonnage: 22.5,
          rate: 108000,
          itemValue: 2430000,
          arrivalDate: "27/08/2026",
          status: "Arrived Earlier",
          tripDetail: {
            tripId: "TRIP-8752",
            vehicleNo: "TN 58 CC 3344",
            driverName: "M. Veeranan",
            driverPhone: "+91 94432 66778",
            transporter: "Pandian Freight",
            lrNo: "PF-44390",
            dispatchDate: "24/08/2026",
            deliveryDate: "27/08/2026",
            status: "Delivered",
            destinationGodown: "South Zone Main Godown",
            loadingPoint: "Madurai Anuppanadi Yard",
          },
        },
      ],
    },
  },
  {
    id: "comp-4",
    sNo: 4,
    date: "28/08/2026",
    orderId: "ORD-2026-0834",
    itemName: "TOOR DHALL DESI 50KG",
    retailerName: "INDORE GRAIN MILLS",
    city: "INDORE",
    state: "MADHYA PRADESH",
    qty: "360 Bags",
    tonnage: 36.0,
    itemValue: 3780000,
    statusTag: "Delivered & Paid",
    order: {
      orderId: "ORD-2026-0834",
      orderDate: "19/08/2026",
      retailerName: "INDORE GRAIN MILLS",
      city: "INDORE",
      state: "MADHYA PRADESH",
      totalOrderTonnage: 36.0,
      totalOrderValue: 3780000,
      paymentStatus: "Paid",
      paidAmount: 3780000,
      balanceAmount: 0,
      items: [
        {
          id: "item-c4-1",
          itemNo: 1,
          itemName: "TOOR DHALL DESI 50KG",
          qty: "360 Bags",
          tonnage: 18.0,
          rate: 105000,
          itemValue: 1890000,
          arrivalDate: "25/08/2026",
          status: "Arrived Earlier",
          tripDetail: {
            tripId: "TRIP-8748",
            vehicleNo: "MP 09 XY 7711",
            driverName: "Deepak Chouhan",
            driverPhone: "+91 98261 44556",
            transporter: "Malwa Express",
            lrNo: "ME-33109",
            dispatchDate: "22/08/2026",
            deliveryDate: "25/08/2026",
            status: "Delivered",
            destinationGodown: "Central Godown - Unit 1",
            loadingPoint: "Indore Mandi",
          },
        },
        {
          id: "item-c4-2",
          itemNo: 2,
          itemName: "MASOOR WHOLE PREMIUM 50KG",
          qty: "360 Bags",
          tonnage: 18.0,
          rate: 105000,
          itemValue: 1890000,
          arrivalDate: "28/08/2026",
          status: "Arrived Earlier",
          tripDetail: {
            tripId: "TRIP-8762",
            vehicleNo: "MP 09 YY 9922",
            driverName: "Rajesh Sahu",
            driverPhone: "+91 98261 88990",
            transporter: "Malwa Express",
            lrNo: "ME-33240",
            dispatchDate: "25/08/2026",
            deliveryDate: "28/08/2026",
            status: "Delivered",
            destinationGodown: "Central Godown - Unit 1",
            loadingPoint: "Indore Mandi",
          },
        },
      ],
    },
  },
];

/* ================= HELPER METHODS ================= */

export const getPurchaseDataByFilter = (
  filterType: PurchaseReportFilterType
): TodayArrivalItem[] => {
  switch (filterType) {
    case "today_arrival":
      return DUMMY_PURCHASE_DATA;
    case "pending_orders":
      return DUMMY_PENDING_ORDERS_DATA;
    case "pending_payments":
      return DUMMY_PENDING_PAYMENTS_DATA;
    case "completed":
      return DUMMY_COMPLETED_DATA;
    default:
      return DUMMY_PURCHASE_DATA;
  }
};

export const getPurchaseFilterCounts = () => ({
  today_arrival: DUMMY_PURCHASE_DATA.length,
  pending_orders: DUMMY_PENDING_ORDERS_DATA.length,
  pending_payments: DUMMY_PENDING_PAYMENTS_DATA.length,
  completed: DUMMY_COMPLETED_DATA.length,
});

export const PurchaseReportService = {
  getPurchaseReportData: async (params?: {
    fromDate?: string;
    toDate?: string;
    partyName?: string;
    filterType?: PurchaseReportFilterType;
  }): Promise<{ success: boolean; data: TodayArrivalItem[] }> => {
    await new Promise((resolve) => setTimeout(resolve, 200));

    const baseData = getPurchaseDataByFilter(params?.filterType || "today_arrival");
    let filtered = [...baseData];

    if (params?.fromDate && params?.toDate) {
      const from = dayjs(params.fromDate);
      const to = dayjs(params.toDate);
      if (from.isValid() && to.isValid()) {
        filtered = filtered.filter((row) => {
          const parts = row.date.split("/");
          if (parts.length === 3) {
            const rowDate = dayjs(`${parts[2]}-${parts[1]}-${parts[0]}`);
            return (
              (rowDate.isAfter(from) || rowDate.isSame(from, "day")) &&
              (rowDate.isBefore(to) || rowDate.isSame(to, "day"))
            );
          }
          return true;
        });
      }
    }

    if (params?.partyName) {
      const term = params.partyName.toLowerCase();
      filtered = filtered.filter(
        (row) =>
          row.retailerName.toLowerCase().includes(term) ||
          row.itemName.toLowerCase().includes(term) ||
          row.orderId.toLowerCase().includes(term) ||
          row.city.toLowerCase().includes(term)
      );
    }

    return {
      success: true,
      data: filtered,
    };
  },
};
